### ISSUE TITLE
Issue after upgrading library from v2.0.6 to v2.47.1

### ISSUE THREAD

**Issue by murilozilli** [chargebee/chargebee-typescript#61]
Issue happens when I call `nest start --watch`(local environment)
```
node_modules/chargebee-typescript/lib/process_wait.d.ts:1:23 - error TS2688: Cannot find type definition file for 'q'.

1 /// <reference types="q" />
```

My code is pretty simple
```
import { Injectable } from '@nestjs/common';
import { ChargeBee } from 'chargebee-typescript';

export class ChargebeeService {
    chargebee: ChargeBee;
    constructor(
    ) {
        this.chargebee = new ChargeBee();
        this.chargebee.configure({ site: process.env.CHARGE_BEE_SITE, api_key: process.env.CHARGE_BEE_API_KEY });
    }
````

**Comment by cb-alish** [comment]
Hi @murilozilli, this might be due to `"@types/q"` being a direct dependency in version `v2.0.6`, but later moved to `devDependencies` due to past issues (Ref: [https://github.com/chargebee/chargebee-typescript/issues/55](https://github.com/chargebee/chargebee-typescript/issues/55)).

Could you try installing the `devDependencies` by running `npm install --include=dev` and let us know if the issue still occurs?

**Comment by cb-alish** [comment]
Hi @murilozilli, correct me if I'm wrong, but I believe this only installs the `devDependencies` for your project, not for third-party packages. I was able to reproduce this issue, and running the following command resolves it:

```sh
yarn add @types/q
```

We’ve encountered this issue with `q` types. However, few existing users refer to this as the native promise type, and moving it to dependencies from `devDependencies` could break their types. It’s been fixed in the latest major release of `chargebee-node 3.x.x`, which now supports TypeScript and uses native JS Promises. You might want to consider [migrating](https://github.com/chargebee/chargebee-node/wiki/Migration-guide-for-v3) if possible.

**Comment by murilozilli** [comment]
Thanks, adding `yarn add @types/q` fixed the issue.
